// Generated by CoffeeScript 1.6.3
jQuery(function() {
  $(".pagination a").click(function(e) {
    e.preventDefault();
    if (!$(this).parent().hasClass("previous") && !$(this).parent().hasClass("next")) {
      $(this).parent().siblings("li").removeClass("active");
      return $(this).parent().addClass("active");
    }
  });
  return $('.panel-content').scroll(function() {
    var sidebar;
    sidebar = $('.docs-sidebar');
    if ($(window).width() > 767) {
      console.log($(window).width());
      if ($('.panel-content').scrollTop() >= 320) {
        sidebar.addClass("affix");
      }
      if ($('.panel-content').scrollTop() < 320) {
        return sidebar.removeClass("affix");
      }
    }
  });
});
