// Generated by CoffeeScript 1.6.3
$(document).ready(function() {
  return $('[data-furatto="toolbar"]').each(function() {
    return $(this).toolbar({
      content: $(this).data('content'),
      position: $(this).data('position') || 'top',
      hideOnClick: true,
      theme: $(this).data('theme')
    });
  });
});
